In [9]:
name = "Alice"  #string
age = 20        # integer
height = 5.9    # float
is_student = True # boolean

print(f"Name: {name}, Age: {age}, Height: {height}, Student: {is_student}")


Name: Alice, Age: 20, Height: 5.9, Student: True


In [15]:
num = int(input("Enter a number: "))
if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")


Enter a number:  5


The number is positive.


In [17]:
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")


Enter a number:  2


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [19]:
fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes"]
print("Fruit list:", fruits)
fruits.append("Pineapple")
print("After adding a fruit:", fruits)
fruits.remove("Banana")
print("After removing a fruit:", fruits)
print("Third fruit:", fruits[2])
fruits.sort()
print("Sorted list:", fruits)


Fruit list: ['Apple', 'Banana', 'Mango', 'Orange', 'Grapes']
After adding a fruit: ['Apple', 'Banana', 'Mango', 'Orange', 'Grapes', 'Pineapple']
After removing a fruit: ['Apple', 'Mango', 'Orange', 'Grapes', 'Pineapple']
Third fruit: Orange
Sorted list: ['Apple', 'Grapes', 'Mango', 'Orange', 'Pineapple']


In [21]:
numbers = (10, 20, 30, 40, 50)
print("Original tuple:", numbers)
print("Second number:", numbers[1])
if 30 in numbers:
    print("30 is in the tuple.")
else:
    print("30 is not in the tuple.")
print("Length of tuple:", len(numbers))
numbers_list = list(numbers)
numbers_list.append(60)
print("Tuple after adding a number (converted to list):", numbers_list)


Original tuple: (10, 20, 30, 40, 50)
Second number: 20
30 is in the tuple.
Length of tuple: 5
Tuple after adding a number (converted to list): [10, 20, 30, 40, 50, 60]


In [23]:
students_marks = {
    "Alice": 85,
    "Bob": 90,
    "Charlie": 78
}
print("Student marks:", students_marks)
print("Marks of Bob:", students_marks["Bob"])
students_marks["David"] = 88
print("After adding a new student:", students_marks)
students_marks["Alice"] = 95
print("After updating Alice's marks:", students_marks)
del students_marks["Charlie"]
print("After removing Charlie:", students_marks)
if "Bob" in students_marks:
    print("Bob's marks are available.")
else:
    print("Bob is not in the dictionary.")


Student marks: {'Alice': 85, 'Bob': 90, 'Charlie': 78}
Marks of Bob: 90
After adding a new student: {'Alice': 85, 'Bob': 90, 'Charlie': 78, 'David': 88}
After updating Alice's marks: {'Alice': 95, 'Bob': 90, 'Charlie': 78, 'David': 88}
After removing Charlie: {'Alice': 95, 'Bob': 90, 'David': 88}
Bob's marks are available.


In [25]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
print("Union:", set1 | set2)
print("Intersection:", set1 & set2)
print("Difference:", set1 - set2)
print("Symmetric Difference:", set1 ^ set2)


Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference: {1, 2, 3}
Symmetric Difference: {1, 2, 3, 6, 7, 8}


In [27]:
def find_largest(numbers):
    return max(numbers)
sample_list = [10, 25, 3, 45, 7]
largest_number = find_largest(sample_list)
print("The largest number is:", largest_number)


The largest number is: 45


In [29]:
squares_of_even_numbers = [x**2 for x in range(1, 21) if x % 2 == 0]
print(squares_of_even_numbers)


[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [31]:
product = lambda x, y: x * y
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
result = product(num1, num2)
print(f"The product of {num1} and {num2} is: {result}")


Enter the first number:  4
Enter the second number:  6


The product of 4.0 and 6.0 is: 24.0


In [35]:
import numpy as np
#Create a one-dimensional NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)
print("Dimensions:", array_1d.ndim)

#Create a two-dimensional NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)
print("Dimensions:", array_2d.ndim)

#Create a three-dimensional NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)
print("Dimensions:", array_3d.ndim)


1D Array:
[1 2 3 4 5]
Shape: (5,)
Dimensions: 1

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [37]:
import numpy as np
array = np.random.randint(0, 10, size=(5, 5))
print("5x5 Array of random integers:")
print(array)
element_1 = array[0, 0]
print("\nElement at (0, 0):", element_1)
row_2 = array[1, :]
print("\nSecond row:", row_2)
col_3 = array[:, 2]
print("\nThird column:", col_3)
sub_array = array[1:3, 1:3]
print("\n2x2 Sub-array from rows 1 to 2 and columns 1 to 2:")
print(sub_array)


5x5 Array of random integers:
[[6 5 3 5 8]
 [1 8 6 0 0]
 [3 6 6 8 3]
 [7 6 9 7 4]
 [7 7 8 1 2]]

Element at (0, 0): 6

Second row: [1 8 6 0 0]

Third column: [3 6 6 9 8]

2x2 Sub-array from rows 1 to 2 and columns 1 to 2:
[[8 6]
 [6 6]]


In [39]:
import numpy as np
array = np.arange(1, 17).reshape(4, 4)
print("4x4 Array of numbers from 1 to 16:")
print(array)
first_row = array[0, :]
print("\nFirst row:", first_row)
last_column = array[:, -1]
print("\nLast column:", last_column)
sub_array_1 = array[:2, :2]
print("\nSub-array (first 2 rows, first 2 columns):")
print(sub_array_1)
sub_array_2 = array[1:3, 1:3]
print("\nSub-array (middle 2x2):")
print(sub_array_2)


4x4 Array of numbers from 1 to 16:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First row: [1 2 3 4]

Last column: [ 4  8 12 16]

Sub-array (first 2 rows, first 2 columns):
[[1 2]
 [5 6]]

Sub-array (middle 2x2):
[[ 6  7]
 [10 11]]


In [41]:
import numpy as np
array_2d = np.arange(1, 13).reshape(6, 2)
print("2D Array (6, 2):")
print(array_2d)
array_3d = array_2d.reshape(2, 3, 2)
print("\nReshaped 3D Array (2, 3, 2):")
print(array_3d)
flattened_array = array_3d.flatten()
print("\nFlattened Array:")
print(flattened_array)


2D Array (6, 2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped 3D Array (2, 3, 2):
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [43]:
import numpy as np
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
array_1d = np.array([10, 20, 30])
result = array_2d + array_1d
print("2D Array:")
print(array_2d)
print("\n1D Array:")
print(array_1d)
print("\nResult after broadcasting and addition:")
print(result)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array:
[10 20 30]

Result after broadcasting and addition:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [45]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
addition_result = A + B
subtraction_result = A - B
multiplication_result = A * B
division_result = A / B
print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nElement-wise Addition (A + B):")
print(addition_result)
print("\nElement-wise Subtraction (A - B):")
print(subtraction_result)
print("\nElement-wise Multiplication (A * B):")
print(multiplication_result)
print("\nElement-wise Division (A / B):")
print(division_result)


Array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division (A / B):
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
